# Chapter 4 Notes: NumPy Basics — Arrays and Vectorized Computation

These notes summarize the key ideas from Chapter 4 of *Python for Data Analysis* by Wes McKinney.

## Chapter Overview

This chapter introduces **NumPy**, one of the most important libraries in Python for numerical computing.

Main topics:
- NumPy arrays (`ndarray`)
- vectorized computation
- array creation
- data types
- indexing and slicing
- Boolean indexing
- fancy indexing
- transposing arrays
- random number generation
- universal functions
- statistical methods
- sorting and set logic
- file input/output
- linear algebra
- random walk simulation

NumPy is important because it allows fast operations on whole arrays without writing Python loops.

## Why NumPy Matters

NumPy is designed for efficient numerical computation.

### Main advantages:
- faster than regular Python lists for numeric work
- uses less memory
- supports vectorized operations
- works well with large datasets
- provides a foundation for pandas and many other libraries

### Key idea:
Instead of looping through values one at a time, NumPy lets you perform operations on entire arrays at once.

## The NumPy `ndarray`

The main NumPy object is the **ndarray**, which is a multidimensional array.

### Key properties:
- stores homogeneous data (all elements are the same type)
- has a `shape`
- has a `dtype`

### Important attributes:
- `shape` tells the size of each dimension
- `dtype` tells the array’s data type
- `ndim` tells the number of dimensions

## Creating Arrays

Arrays can be created in several ways.

### Common functions:
- `np.array()` converts lists or tuples into arrays
- `np.zeros()` creates an array of zeros
- `np.ones()` creates an array of ones
- `np.empty()` creates an uninitialized array
- `np.arange()` works like Python’s `range()` but returns an array
- `np.full()` creates an array filled with one value
- `np.eye()` creates an identity matrix

### Important idea:
Nested lists create multidimensional arrays.

## Data Types for Arrays

Every NumPy array has a data type (`dtype`).

### Common types:
- `int32`, `int64`
- `float32`, `float64`
- `bool`
- `object`
- string types

### Important idea:
NumPy arrays must contain values of one data type.

### Casting
You can convert an array to another type using:
- `astype()`

Examples:
- integers to floats
- floats to integers
- numeric strings to numbers

## Arithmetic with NumPy Arrays

Arithmetic in NumPy is **vectorized**.

This means operations apply element-by-element across the whole array.

### Examples of vectorized operations:
- addition
- subtraction
- multiplication
- division
- powers
- comparisons

### Important idea:
Arithmetic with a scalar applies the scalar to every element in the array.

This is one of the biggest reasons NumPy is fast and useful.

## Basic Indexing and Slicing

NumPy arrays can be indexed similarly to Python lists, but they have more powerful options.

### One-dimensional arrays:
- use standard indexing
- use slicing like `arr[1:5]`

### Important difference from Python lists:
NumPy slices usually return **views**, not copies.

That means changing the slice can change the original array.

### Key point:
If you want an actual copy, use:
- `.copy()`

## Indexing Multidimensional Arrays

For 2D and higher-dimensional arrays, NumPy supports multiple indices.

### Examples of ideas:
- `arr2d[0, 2]` selects one value
- `arr2d[:2]` selects the first two rows
- `arr2d[:, :1]` selects all rows and the first column

### Important idea:
- axis 0 usually refers to rows
- axis 1 usually refers to columns

Slicing multidimensional arrays is a core part of working with NumPy data.

## Boolean Indexing

Boolean indexing selects values based on True/False conditions.

This is very useful for filtering data.

### Example ideas:
- select rows where `names == "Bob"`
- select rows where values are positive
- replace negative values with 0

### Key points:
- comparisons create Boolean arrays
- Boolean arrays must match the axis being indexed
- use `&` for and
- use `|` for or
- use `~` to negate a condition

### Important note:
Do not use Python’s `and` and `or` with NumPy Boolean arrays.

## Fancy Indexing

Fancy indexing means indexing with arrays or lists of integers.

This lets you:
- select rows in a custom order
- select specific positions
- reorder data

### Important idea:
Fancy indexing creates a **copy**, not a view.

That makes it different from slicing.

## Transposing and Swapping Axes

Transposing changes the orientation of an array.

### Common tools:
- `.T` for transpose
- `transpose()` method
- `swapaxes()` to swap dimensions

### Important idea:
Transposing usually returns a **view**, not a copy.

This is especially useful in matrix computations.

## Pseudorandom Number Generation

NumPy provides fast tools for generating random numbers.

### Common methods:
- `standard_normal()`
- `normal()`
- `uniform()`
- `integers()`
- `binomial()`

### Recommended approach:
Use a generator object created with:
- `np.random.default_rng(seed=...)`

### Why use a seed?
A seed makes results reproducible, which is very important in analysis and experiments.

## Universal Functions (ufuncs)

Universal functions, or **ufuncs**, perform fast element-wise operations on arrays.

### Unary ufuncs (one input):
- `sqrt()`
- `exp()`
- `abs()`
- `log()`
- `sign()`

### Binary ufuncs (two inputs):
- `add()`
- `subtract()`
- `multiply()`
- `maximum()`
- `minimum()`

### Important idea:
Ufuncs allow fast calculations across arrays without loops.

## Array-Oriented Programming

NumPy encourages solving problems using whole-array expressions instead of loops.

This is often called **vectorization**.

### Example idea:
A function can be evaluated across an entire grid of x and y values using:
- `meshgrid()`
- vectorized math expressions

This style is concise, fast, and powerful.

## Conditional Logic with `np.where`

`np.where()` is the vectorized version of conditional logic.

It works like:
- choose one value if a condition is True
- choose another value if it is False

### Why it matters:
It is much faster and cleaner than writing list comprehensions or loops for array-based conditions.

This is very useful for:
- replacing values
- recoding categories
- applying rules to arrays

## Mathematical and Statistical Methods

NumPy arrays support many built-in statistics and aggregations.

### Common methods:
- `sum()`
- `mean()`
- `std()`
- `var()`
- `min()`
- `max()`
- `argmin()`
- `argmax()`

### Axis argument
These methods can operate across an axis.

Examples of meaning:
- `axis=0` works down rows
- `axis=1` works across columns

### Cumulative methods:
- `cumsum()`
- `cumprod()`

These return running totals or products.

## Methods for Boolean Arrays

Boolean arrays can be summarized like numeric arrays.

### Useful methods:
- `sum()` counts True values
- `any()` checks whether at least one value is True
- `all()` checks whether every value is True

These methods are helpful for filtering, validation, and condition checks.

## Sorting

NumPy arrays can be sorted.

### Options:
- `arr.sort()` sorts in place
- `np.sort(arr)` returns a sorted copy

### Important idea:
Sorting can also be done along an axis in multidimensional arrays.

Sorting is commonly used before ranking, filtering, or summarizing data.

## Unique Values and Set Logic

NumPy includes useful set-like operations.

### Common functions:
- `np.unique()` returns sorted unique values
- `np.in1d()` checks membership
- `intersect1d()`
- `union1d()`
- `setdiff1d()`
- `setxor1d()`

These are useful for:
- removing duplicates
- checking overlaps
- comparing groups of values

## File Input and Output with Arrays

NumPy can save and load arrays efficiently in binary form.

### Common functions:
- `np.save()` saves one array to `.npy`
- `np.load()` loads an array
- `np.savez()` saves multiple arrays in one archive
- `np.savez_compressed()` saves compressed archives

These tools are useful when storing NumPy arrays directly.

## Linear Algebra

NumPy includes linear algebra tools for matrix operations.

### Common operations:
- `dot()` for matrix multiplication
- `@` operator for matrix multiplication
- `inv()` for inverse
- `det()` for determinant
- `qr()` for QR decomposition
- `solve()` for linear systems
- `svd()` for singular value decomposition

### Important distinction:
- `*` does element-wise multiplication
- `dot()` or `@` does matrix multiplication

## Example: Random Walks

The chapter ends with an example of simulating random walks using NumPy.

### Main idea:
Instead of using a Python loop for each step, NumPy generates many random steps at once and uses:
- `np.where()`
- `cumsum()`

### Why this matters:
This shows how NumPy can make simulations much faster and more concise.

The example also demonstrates how to:
- calculate min and max values
- find first crossing times
- simulate many random walks at once
- summarize simulation results

## Main Takeaway

Chapter 4 introduces NumPy as the foundation for fast numerical and array-based computing in Python.

The most important ideas were:
- arrays are faster and more efficient than Python lists for numerical work
- NumPy supports vectorized operations
- indexing and slicing are powerful and flexible
- Boolean indexing is essential for filtering
- statistical methods work across entire arrays
- `np.where()` handles vectorized conditional logic
- NumPy supports file storage, linear algebra, and simulation

This chapter is important because NumPy thinking carries over into pandas and many other Python data tools.

In [1]:
# Simple Chapter 4 practice examples

import numpy as np

# create arrays
arr = np.array([1, 2, 3, 4])
print(arr)

# vectorized arithmetic
print(arr * 2)
print(arr + 5)

# array statistics
print(arr.mean())
print(arr.sum())

# Boolean indexing
arr2 = np.array([1, -2, 3, -4, 5])
print(arr2[arr2 > 0])

# where
result = np.where(arr2 > 0, 1, 0)
print(result)

# reshape and transpose
matrix = np.arange(6).reshape((2, 3))
print(matrix)
print(matrix.T)

# random numbers
rng = np.random.default_rng(seed=123)
print(rng.standard_normal(5))

[1 2 3 4]
[2 4 6 8]
[6 7 8 9]
2.5
10
[1 3 5]
[1 0 1 0 1]
[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[-0.98912135 -0.36778665  1.28792526  0.19397442  0.9202309 ]
